apiVersion: v1
kind: Service
metadata:
  name: metadata-service
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: metadata-service
  ports:
    - port: 80
      targetPort: 8080
