apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: redis-slave
  name: redis-slave
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  jobLabel: redis-slave
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      k8s-app: redis-slave
